version: "2"

services:
  masternode:
    build: .
    image: ryandub/locust
    container_name: master
    volumes:
      - ./locustfiles:/opt/locustfiles
    ports:
      - "8089:8089"
      - "5557:5557"
      - "5558:5558"
    command: locust --master -f /opt/locustfiles/test.py

  slavenode:
    build: .
    image: ryandub/locust
    network_mode: "host"
    container_name: slave
    volumes:
      - ./locustfiles:/opt/locustfiles
    ports:
      - "8089:8089"
      - "5557:5557"
      - "5558:5558"
    command: locust --slave --master-host=localhost -f /opt/locustfiles/test.py    

  locust:
     build: .
     container_name: locust
     links:
      - "slavenode"
      - "masternode"
